In [1]:

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [2]:
#C:\Users\91915\Basic Python


flatdata = pd.read_csv("Health.csv")
X = flatdata.iloc [:,0:3].values
y = flatdata.iloc [:,3].values
#print(y)
X
y

array(['Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes'],
      dtype=object)

In [3]:
flatdata

Ethnicity  Height (CM)  Weight (Kg) Will survive till 70
0     White        186.0         90.0                  Yes
1   African        185.0         98.0                   No
2     Asian        175.0         80.0                   No
3     White        180.0         88.0                  Yes
4     Asian        178.0          NaN                   No
5     Asian        172.0         72.0                  Yes
6   African        178.0         75.0                   No
7     White          NaN         89.0                  Yes
8   African        186.0         90.0                  Yes

In [10]:
flatdata.isnull().sum()

Ethnicity               0
Height (CM)             1
Weight (Kg)             1
Will survive till 70    0
dtype: int64

In [5]:
from sklearn.preprocessing import LabelEncoder
X_labelencoder = LabelEncoder()
X[:, 0] = X_labelencoder.fit_transform(X[:, 0])
#print (X)

# for y
y_labelencoder = LabelEncoder ()
y = y_labelencoder.fit_transform (y)
print (y)

X

[1 0 0 1 0 1 0 1 1]


array([[2, 186.0, 90.0],
       [0, 185.0, 98.0],
       [1, 175.0, 80.0],
       [2, 180.0, 88.0],
       [1, 178.0, nan],
       [1, 172.0, 72.0],
       [0, 178.0, 75.0],
       [2, nan, 89.0],
       [0, 186.0, 90.0]], dtype=object)

In [6]:
from sklearn.impute import SimpleImputer
missingValueImputer = SimpleImputer (missing_values = np.NaN, strategy = 'mean')  
missingValueImputer = missingValueImputer.fit (X[:,1:3])
X[:,1:3] = missingValueImputer.transform(X[:,1:3])
print(X)

[[2 186.0 90.0]
 [0 185.0 98.0]
 [1 175.0 80.0]
 [2 180.0 88.0]
 [1 178.0 85.25]
 [1 172.0 72.0]
 [0 178.0 75.0]
 [2 180.0 89.0]
 [0 186.0 90.0]]


In [7]:


from sklearn.model_selection import train_test_split
#from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split (X, y, test_size = .20, random_state = 0)





In [8]:

from sklearn.linear_model import LogisticRegression
LRClassifier = LogisticRegression (random_state = 0)
LRClassifier.fit (X_train, y_train)
prediction = LRClassifier.predict (X_test)
from sklearn.metrics import accuracy_score

print(accuracy_score(y_test, prediction))


#prediction 

1.0


In [9]:
from sklearn.metrics import confusion_matrix
confusionMatrix = confusion_matrix (y_test, prediction)

print(confusionMatrix)



[[1 0]
 [0 1]]
