In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")


In [2]:
df1=pd.read_csv('test.csv')

In [3]:
df2=pd.read_csv('train.csv')

In [4]:
df=pd.concat([df2,df1],axis=0).reset_index(drop=True)

In [5]:
df

PassengerId  Survived  Pclass  \
0               1       0.0       3   
1               2       1.0       1   
2               3       1.0       3   
3               4       1.0       1   
4               5       0.0       3   
...           ...       ...     ...   
1304         1305       NaN       3   
1305         1306       NaN       1   
1306         1307       NaN       3   
1307         1308       NaN       3   
1308         1309       NaN       3   

                                                   Name     Sex   Age  SibSp  \
0                               Braund, Mr. Owen Harris    male  22.0      1   
1     Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                                Heikkinen, Miss. Laina  female  26.0      0   
3          Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                              Allen, Mr. William Henry    male  35.0      0   
...                                                 ...     ...   ...    ...   
1304                                 Spector, Mr. Woolf    male   NaN      0   
1305                       Oliva y Ocana, Dona. Fermina  female  39.0      0   
1306                       Saether, Mr. Simon Sivertsen    male  38.5      0   
1307                                Ware, Mr. Frederick    male   NaN      0   
1308                           Peter, Master. Michael J    male   NaN      1   

      Parch              Ticket      Fare Cabin Embarked  
0         0           A/5 21171    7.2500   NaN        S  
1         0            PC 17599   71.2833   C85        C  
2         0    STON/O2. 3101282    7.9250   NaN        S  
3         0              113803   53.1000  C123        S  
4         0              373450    8.0500   NaN        S  
...     ...                 ...       ...   ...      ...  
1304      0           A.5. 3236    8.0500   NaN        S  
1305      0            PC 17758  108.9000  C105        C  
1306      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
1307      0              359309    8.0500   NaN        S  
1308      1                2668   22.3583   NaN        C  

[1309 rows x 12 columns]

In [6]:
df2.shape

(891, 12)

In [7]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [8]:
missing_values=df2.isnull().sum()
missing_values

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [9]:
df2['Embarked'].unique()

array(['S', 'C', 'Q', nan], dtype=object)

In [10]:
df2=df2.drop(['PassengerId','Name','Cabin','Ticket'],axis=1)
df2

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [11]:
df2['Embarked'].isnull().sum()

2

In [12]:
df2['Age'] = df2['Age'].fillna(df2['Age'].mean())

In [13]:
from sklearn.preprocessing import LabelEncoder
df2_labelencoder = LabelEncoder()
df2["Sex"] = df2_labelencoder.fit_transform(df2["Sex"])
df2["Embarked"] = df2_labelencoder.fit_transform(df2["Embarked"])
df2
#male=1,female=0
#s=2,c=0,q=1,nan=3

Survived  Pclass  Sex        Age  SibSp  Parch     Fare  Embarked
0           0       3    1  22.000000      1      0   7.2500         2
1           1       1    0  38.000000      1      0  71.2833         0
2           1       3    0  26.000000      0      0   7.9250         2
3           1       1    0  35.000000      1      0  53.1000         2
4           0       3    1  35.000000      0      0   8.0500         2
..        ...     ...  ...        ...    ...    ...      ...       ...
886         0       2    1  27.000000      0      0  13.0000         2
887         1       1    0  19.000000      0      0  30.0000         2
888         0       3    0  29.699118      1      2  23.4500         2
889         1       1    1  26.000000      0      0  30.0000         0
890         0       3    1  32.000000      0      0   7.7500         1

[891 rows x 8 columns]

In [14]:
df2["Embarked"].unique()

array([2, 0, 1, 3])

In [15]:
df2['Age']=df2['Age'].astype(int)

In [16]:
df2

Survived  Pclass  Sex  Age  SibSp  Parch     Fare  Embarked
0           0       3    1   22      1      0   7.2500         2
1           1       1    0   38      1      0  71.2833         0
2           1       3    0   26      0      0   7.9250         2
3           1       1    0   35      1      0  53.1000         2
4           0       3    1   35      0      0   8.0500         2
..        ...     ...  ...  ...    ...    ...      ...       ...
886         0       2    1   27      0      0  13.0000         2
887         1       1    0   19      0      0  30.0000         2
888         0       3    0   29      1      2  23.4500         2
889         1       1    1   26      0      0  30.0000         0
890         0       3    1   32      0      0   7.7500         1

[891 rows x 8 columns]

In [17]:
X_train = df2.iloc [:,1:8].values
y_train = df2.iloc [:,0].values

In [18]:
X_train

array([[ 3.    ,  1.    , 22.    , ...,  0.    ,  7.25  ,  2.    ],
       [ 1.    ,  0.    , 38.    , ...,  0.    , 71.2833,  0.    ],
       [ 3.    ,  0.    , 26.    , ...,  0.    ,  7.925 ,  2.    ],
       ...,
       [ 3.    ,  0.    , 29.    , ...,  2.    , 23.45  ,  2.    ],
       [ 1.    ,  1.    , 26.    , ...,  0.    , 30.    ,  0.    ],
       [ 3.    ,  1.    , 32.    , ...,  0.    ,  7.75  ,  1.    ]])

In [19]:
y_train

array([0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1,

In [20]:
df1
df1=df1.drop(['PassengerId','Name','Cabin','Ticket'],axis=1)
df1




Pclass     Sex   Age  SibSp  Parch      Fare Embarked
0         3    male  34.5      0      0    7.8292        Q
1         3  female  47.0      1      0    7.0000        S
2         2    male  62.0      0      0    9.6875        Q
3         3    male  27.0      0      0    8.6625        S
4         3  female  22.0      1      1   12.2875        S
..      ...     ...   ...    ...    ...       ...      ...
413       3    male   NaN      0      0    8.0500        S
414       1  female  39.0      0      0  108.9000        C
415       3    male  38.5      0      0    7.2500        S
416       3    male   NaN      0      0    8.0500        S
417       3    male   NaN      1      1   22.3583        C

[418 rows x 7 columns]

In [21]:
df1.isnull().sum()

Pclass       0
Sex          0
Age         86
SibSp        0
Parch        0
Fare         1
Embarked     0
dtype: int64

In [22]:
from sklearn.preprocessing import LabelEncoder
df1_labelencoder = LabelEncoder()
df1["Sex"] = df1_labelencoder.fit_transform(df1["Sex"])
df1["Embarked"] = df1_labelencoder.fit_transform(df1["Embarked"])
df1

Pclass  Sex   Age  SibSp  Parch      Fare  Embarked
0         3    1  34.5      0      0    7.8292         1
1         3    0  47.0      1      0    7.0000         2
2         2    1  62.0      0      0    9.6875         1
3         3    1  27.0      0      0    8.6625         2
4         3    0  22.0      1      1   12.2875         2
..      ...  ...   ...    ...    ...       ...       ...
413       3    1   NaN      0      0    8.0500         2
414       1    0  39.0      0      0  108.9000         0
415       3    1  38.5      0      0    7.2500         2
416       3    1   NaN      0      0    8.0500         2
417       3    1   NaN      1      1   22.3583         0

[418 rows x 7 columns]

In [23]:
df1['Fare'] = df1['Fare'].fillna(df1['Fare'].mean())

In [24]:
#from sklearn.impute import SimpleImputer
#missingValueImputer = SimpleImputer (missing_values = np.Nan, strategy = 'mean')  
#missingValueImputer = missingValueImputer.fit (df1['Age'])
#df1['Age'] = missingValueImputer.transform(df1['Age'])
#print(df1)

In [25]:
df1['Age'] = df1['Age'].fillna(df1['Age'].mean())

In [26]:
df1

Pclass  Sex       Age  SibSp  Parch      Fare  Embarked
0         3    1  34.50000      0      0    7.8292         1
1         3    0  47.00000      1      0    7.0000         2
2         2    1  62.00000      0      0    9.6875         1
3         3    1  27.00000      0      0    8.6625         2
4         3    0  22.00000      1      1   12.2875         2
..      ...  ...       ...    ...    ...       ...       ...
413       3    1  30.27259      0      0    8.0500         2
414       1    0  39.00000      0      0  108.9000         0
415       3    1  38.50000      0      0    7.2500         2
416       3    1  30.27259      0      0    8.0500         2
417       3    1  30.27259      1      1   22.3583         0

[418 rows x 7 columns]

In [27]:
df1.isnull().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
dtype: int64

In [28]:
df1['Age']=df1['Age'].astype(int)

In [29]:
X_test=df1.iloc [:,0:7].values

In [30]:
X_test

array([[ 3.    ,  1.    , 34.    , ...,  0.    ,  7.8292,  1.    ],
       [ 3.    ,  0.    , 47.    , ...,  0.    ,  7.    ,  2.    ],
       [ 2.    ,  1.    , 62.    , ...,  0.    ,  9.6875,  1.    ],
       ...,
       [ 3.    ,  1.    , 38.    , ...,  0.    ,  7.25  ,  2.    ],
       [ 3.    ,  1.    , 30.    , ...,  0.    ,  8.05  ,  2.    ],
       [ 3.    ,  1.    , 30.    , ...,  1.    , 22.3583,  0.    ]])

In [31]:

#from sklearn.linear_model import LogisticRegression
#LRClassifier = LogisticRegression (random_state = 0)
#LRClassifier.fit (X_train, y_train)
#prediction = LRClassifier.predict (X_test)
#from sklearn.metrics import accuracy_score
#print(accuracy_score(y_test, prediction))

In [32]:

from sklearn.linear_model import LinearRegression
lnr = LinearRegression()
lnr.fit (X_train, y_train ) 
predicted_y = lnr.predict(X_test)
for var in predicted_y:
    if(var<0.6):
        var=0
    else:
        var=1     
#print("predicted y records:")
print(predicted_y)

[ 0.10102207  0.45825326  0.10896804  0.10823495  0.58750259  0.18367796
  0.63179409  0.23109038  0.73473065  0.06479552  0.09063924  0.3423555
  0.95827126  0.03302008  0.81314234  0.83415642  0.26609322  0.20968975
  0.57433682  0.57838089  0.32576146  0.19380518  0.94433192  0.54751256
  0.88199103 -0.06459867  1.04956451  0.20389906  0.37262158  0.07908861
  0.108299    0.21911058  0.5091623   0.527373    0.47004732  0.22706303
  0.59835184  0.65064669  0.12006062  0.10481585  0.09020331  0.43516692
  0.02692833  0.76933888  0.82220903  0.11960119  0.41635547  0.12416171
  0.85075357  0.53177717  0.43831777  0.34676643  0.7304013   0.86521602
  0.32955361  0.06374783  0.06168581  0.11952098  0.05168178  1.04401048
  0.16591817  0.25023574  0.16008495  0.67814753  0.55270701  0.77167248
  0.70135526  0.34134869  0.49708598  0.7284949   0.66657345  0.14275542
  0.60410607  0.51421981  1.03496095  0.54466539  0.09068422  0.71511818
  0.26167126  0.66657345  0.24047889  0.23650918  0.

In [34]:
#from sklearn.metrics import confusion_matrix
#confusionMatrix = confusion_matrix (y_test, prediction)

#print(confusionMatrix)



In [ ]:
sns.boxplot(y=df['Age'])
plt.show()

In [ ]:
q1,q3=df['Age'].quantile([.25,.75])
iqr=q3-q1
ll=q1-1.5*(iqr)
ul=q3+1.5*(iqr)

In [ ]:
df3=df[df['Age']>ul]

In [ ]:
df3

In [ ]:
sns.boxplot(y=df3['Age'])
plt.show()

In [ ]:
df['Age']=np.where(df['Age']>ul,ul,df['Age'])

In [ ]:
sns.boxplot(y=df['Age'])
plt.show()

In [ ]:
df['Age']=np.where(df['Age']<ll,ll,df['Age'])

In [ ]:
sns.boxplot(y=df['Age'])
plt.show()

In [ ]:
plt.figure(figsize=(4,4))
sns.countplot(df['Survived'])
plt.show()

In [ ]:
df

In [ ]:
df=df.dropna()

In [ ]:
df

In [ ]:
df=df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Fare','Embarked'],axis=1)

In [ ]:
df

In [ ]:
df=pd.get_dummies(df,drop_first=True)

In [ ]:
df

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
y=df['Survived']

In [ ]:
x=df[['Age','Pclass','Sex_male']]

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,stratify=y)

In [ ]:
print(x_train.shape)
print(x_test.shape)

In [ ]:
print(y_train.value_counts(normalize=True).round(2))
print(y_test.value_counts(normalize=True).round(2))

In [ ]:
from sklearn.ensemble import RandomForestRegressor

In [ ]:
rfr=RandomForestRegressor()

In [ ]:
rfr.fit(x_train,y_train)

In [ ]:
y_pred=rfr.predict(x_test)

In [ ]:
from sklearn.metrics import mean_squared_error

In [ ]:
 mean_squared_error(y_test,y_pred)